select* from customer limit 50

--Q1. What is the total revenue generated by male vs female customers?
select gender, ROUND((SUM(purchase_amount)),2) as revenue
from customer
group by gender

--Q2. Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating)::numeric,2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5

--this highlights the high reviewed items which can be sold at premium prices also.

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, ROUND(AVG(purchase_amount),2) as "Average Purchase Amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers & non- susbcribers.
select subscription_status, 
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend, 
ROUND((SUM(purchase_amount)),2) as total_revenue
from customer
group by subscription_status
order by avg_spend, total_revenue desc

--Q6. Which 5 products have the highest % of purchases with discounts applied?
-- here you have to check how many times an item was sold at a discount out of the total items that item sold.
-- for ex: discount_rate=50% ,, so it means out of the 10 times that item was sold, 5 times it was sold at a discount.

--so this shows which product rely heavily on discounts
select item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
--helps in customer segmentation for business prospects
--used CTE common table extension which are reusuable temporary tables.
with customer_type as(
select customer_id, previous_purchases,
CASE 
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	 ELSE 'Loyal'
	 END as customer_segment
from customer
)
select customer_segment, count(*) as count_segment
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
--advanced query, used window function 
--we used ROW_NUMBER and not RANK or DENSERANK function because they would give same rank to equal values,
-- ex: 161,161 belt sunglasses both would same rank 2.
--partition by function divides data into groups so window functions operate independently within each group.
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3

--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
--imp.question as : if loyal customers are subscribing, its good for the business
--if they are not subscribing,then there must be an issue with the subscription model/pricing
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
--it tells us which demographic is most valuable to the business.
select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
